# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia coverage.jl
